[package]
name = "gpt"
version = "0.1.2"
description = "A library to read GPT headers and partition information from disks and disk images."
documentation = "none?"
authors = ["Chris Ober <obercgit@gmail.com>"]

[dependencies]
uuid = "~0.4"
byteorder = "~1.0"
crc = "~1.4"
serde = "~0.9"
serde_json = "~0.9"
serde_derive = "~0.9"