[package]
name = "gpt"
version = "0.1.7"
description = "A library to read GPT headers and partition information from disks and disk images."
documentation = "https://docs.rs/gpt"
authors = ["Chris Ober <obercgit@gmail.com>", "Chris Holcombe <xfactor973@gmail.com>"]
license = "MIT"
homepage = "https://github.com/Quyzi/gpt"

[dependencies]
uuid = "~0.4"
byteorder = "~1.0"
crc = "~1.4"
serde = "~0.9"
serde_json = "~0.9"
serde_derive = "~0.9"