[package]
name = "gpt"
version = "0.2.2"
description = "A library to read GPT headers and partition information from disks and disk images."
documentation = "https://docs.rs/gpt"
authors = ["Chris Ober <obercgit@gmail.com>", "Chris Holcombe <xfactor973@gmail.com>", "Luca Bruno <lucab@debian.org>"]
license = "MIT"
homepage = "https://github.com/Quyzi/gpt"

[dependencies]
bitflags = "~1.0"
byteorder = "~1.2"
crc = "~1.8"
lazy_static = "~1.0"
log = "~0.4"
uuid = { version = "~0.6", features = ["v4"] }

[dev-dependencies]
simplelog = "~0.5"
tempfile = "~3.0"
